#ifndef QUICK_CONFIG_H
#define QUICK_CONFIG_H

#include "vex.h"

#define LEFT_DRIVE_MOTOR_PORT PORT1
#define RIGHT_DRIVE_MOTOR_PORT PORT2
#define CLAW_MOTOR_PORT PORT6
#define ARM_MOTOR_PORT PORT3

#define DRIVE_MIN_SPEED 100
#define DRIVE_MAX_SPEED 300
#define DRIVE_P_COSNT 1.8
#define TURN_MIN_SPEED 50
#define TURN_MAX_SPEED 250
#define TURN_P_CONST 1.7

#endif